# Generated by Django 3.1.4 on 2021-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf_idf',
            name='vector',
            field=models.FilePathField(path='/home/mimr/sauron/var/analitycs/'),
        ),
    ]
