# Generated by Django 3.0.6 on 2021-01-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
