# Generated by Django 3.1.4 on 2021-01-05 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='juego',
            new_name='juegos',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='titulo',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='tipo',
            field=models.CharField(default='Cualsea', max_length=30, verbose_name='Tipo de recomendación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='retroalimentacion',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
