# Generated by Django 3.1.4 on 2021-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0002_auto_20210105_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='vector_perfil',
            field=models.CharField(max_length=70, null=True, verbose_name='Vector de perfil del usuario'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='vector_pesos',
            field=models.CharField(max_length=70, null=True, verbose_name='Vector de pesos del usuario'),
        ),
    ]
