# Generated by Django 3.0.6 on 2021-01-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjug', '0002_auto_20210119_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='alt',
            field=models.CharField(max_length=200, verbose_name='Texto alternativo a la imagen'),
        ),
        migrations.AlterField(
            model_name='listgeneros',
            name='listgenero',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listgeneros',
            name='listplataforma',
            field=models.CharField(max_length=200),
        ),
    ]
